method: 'grid'
name: 'seo_suffix'
metric: 
    name: 'eval/product_rank'
    goal: 'minimize'   

parameters: 
  seed:
    value: 42

  model: 
    value: mistral-7b # deepseek-7b # vicuna-7b # mistral-7b # can be ignored if using args
  mode:
    value: "suffix" # Choices: ["paraphrase", "suffix"]

  batch_size: 
    value: 5
  length: 
    value: 30 # 30 for suffix, 50 for paraphrase
  temperature:
    value: 0.1
  lr: 
    value: 0.03
  topk: 
    value: 10
  num_iter: 
    value: 2000
  test_iter: 
    value: 100
  precision: 
    value: 16
  fluency:
    value: 1
  ngram:
    value: 5 # 10
  target:
    value: 50
  similarity:
    value: 1 # not used

  iter_steps:
    value: [0, 50, 200, 500, 1500]
  noise_stds:
    value: [0.1, 0.05, 0.01, 0.001, 0.01]  # [1, 0.5, 0.1, 0.05, 0.01]
  # result_dir: 
  #   value: "result"
  catalog: 
    value: "books" # Choices: ["coffee_machines", "books", "cameras"] # can be ignored if using args
  random_order: 
    value: True 
  random_inference:
    values: [True]
  target_product_idx: 
    values: [1,2,3,4,5,6,7,8,9,10]
  user_msg_type: 
    value: "default" # Choices: ["default", "custom"]

  result_dir:
    value: "result/suffix/v1"

  comment:
    value: "main experiment"
